### ISSUE TITLE
config.json nicht gefunden

### ISSUE THREAD

**Issue by chrischivlog** [ifheroes/Discord-website-bot#1]
Hallo Luca habe den ersten test mal auf meiner Lokalen Maschine durchgeführt allerdings hat es dort nicht Funktioniert er gab folgenden Fehler aus:

`Traceback (most recent call last):
  File "c:\Users\Christopher\Documents\GitHub Desktop\Discord-website-bot\main.py", line 6, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'`

Kann das Problem eventuell bei mir liegen habe eine config.json erstellt mit allen Daten und die gleiche Formatierung verwendet.

**Comment by EckigerLuca** [comment]
Hey, in der `.gitigore` ist extra eingetragen, dass die config.json nicht mit hochgeladen wird. Deswegen ja auch der Eintrag in der README. Eigentlich sollte es funktionieren wenn die config.json im Stammverzeichnis ist.

**Comment by chrischivlog** [comment]
Ok, ich hab sie ja auch extra nochmal erstellt 
![image](https://user-images.githubusercontent.com/16624279/132049980-22e27a40-6131-4069-8968-d87308b036c3.png)

**Comment by chrischivlog** [comment]
Hat leider nicht funktioniert :(

**Comment by EckigerLuca** [comment]
Hmm, so siehts bei mir aus:
![image](https://user-images.githubusercontent.com/63116530/132050088-37c06734-46bc-4214-9a16-73ab57e3f04b.png)

**Comment by EckigerLuca** [comment]
Was passiert, wenn du in Zeile 5 noch ein `./` vor den Dateinamen packst?

**Comment by EckigerLuca** [comment]
Ich hab das ganze jetzt auch mal in der Repository geändert, falls es das war.
