### ISSUE TITLE
Ausbau des Bots auf Discord layout

### ISSUE THREAD

**Issue by chrischivlog** [ifheroes/Discord-website-bot#2]
Hallo Luca, 

gute Arbeit nochmal. Es wäre vielleicht gut wenn du die Nachricht, nach dem sie an unseren Discord Channel geschickt wurde und in die Json Datei eingetragen wurde, anders formatierst. Diese Funktion wird jetzt nicht dringend benötigt aber schön für ein besseres layout auf Discord.

Grüße chris

**Comment by EckigerLuca** [comment]
Hallo,

Was genau meinst du? Soll der Bot die Nachricht löschen und erneut senden, nur als Text mit dem Bild als Anhang?

**Comment by EckigerLuca** [comment]
Oder direkt als Embed?

**Comment by chrischivlog** [comment]
> Hallo,
> 
> Was genau meinst du? Soll der Bot die Nachricht löschen und erneut senden, nur als Text mit dem Bild als Anhang?

![Screenshot_2](https://user-images.githubusercontent.com/16624279/132139383-29fe3e06-57d0-4331-87c6-582bf1d9a095.png)
![Screenshot_1](https://user-images.githubusercontent.com/16624279/132139384-5b99bb80-c7f0-42fe-a4d6-c525c3803198.png)

**Comment by chrischivlog** [comment]
> Oder direkt als Embed?

Meinst du direkt über die Webseite?

**Comment by EckigerLuca** [comment]
Ich meinte jetzt, dass nachdem der Codeblock verarbeitet wurde, dieser gelöscht und durch ein Embed ersetzt wird. Aber da war ich wohl falsch. Ich werde mal versuchen, dass ganze ohne Codeblock und wie auf den Screenshots umzusetzen.

**Comment by chrischivlog** [comment]
> Ich meinte jetzt, dass nachdem der Codeblock verarbeitet wurde, dieser gelöscht und durch ein Embed ersetzt wird. Aber da war ich wohl falsch. Ich werde mal versuchen, dass ganze ohne Codeblock und wie auf den Screenshots umzusetzen. 

Achso ja das wäre eine Möglichkeit 👍

**Comment by EckigerLuca** [comment]
> > Ich meinte jetzt, dass nachdem der Codeblock verarbeitet wurde, dieser gelöscht und durch ein Embed ersetzt wird. Aber da war ich wohl falsch. Ich werde mal versuchen, dass ganze ohne Codeblock und wie auf den Screenshots umzusetzen. 
> 
> Achso ja das wäre eine Möglichkeit 👍

Ich werde denk ich mal beides kombinieren
